name: Create xValidate for older browsers...
on:
    push:
        branches:
            - actions
    pull_request:
        branches:
            - actions

jobs:
    build:
        name: Creating Babel build...
        runs-on: ubuntu-latest
        steps:
          - name: Downloading current version of Node.js...
            run: sudo apt-get install -y nodejs
          - name: Installing Babel and getting config...
            uses: ./package.json
            run: npm install
          - name: Get Babel config and run build
            uses: ./babel.config.json
            uses: ./src/
            run: npm run build
          - name: Saving build output to dist folder...
            uses: actions/upload-artifact@v1
            with:
                name: dist
                path: dist
