name: Create xValidate for older browsers...
on:
    push:
        branches:
            - actions
    pull_request:
        branches:
            - actions

jobs:
    build:
        name: Creating Babel build...
        runs-on: ubuntu-latest
        steps:
          - name: Downloading current version of Node.js...
            run: sudo apt-get install -y nodejs
          - name: Installing Babel and getting config...
            run: wget https://raw.githubusercontent.com/xman40100/xValidate/actions/package.json && npm install
          - name: Getting Babel config...
            run: wget https://raw.githubusercontent.com/xman40100/xValidate/actions/babel.config.json
          - name: Running build using preset.
            run: npm run build
          - name: Saving build output to dist folder...
            uses: actions/upload-artifact@v1
            with:
                name: dist
                path: dist
