name: Create xValidate for older browsers...
on:
    push:
        branches:
            - actions
    pull_request:
        branches:
            - actions

jobs:
    build:
        name: Creating Babel build...
        runs-on: ubuntu-latest
        steps:
          - name: Downloading current version of Node.js...
            run: apt-get install -y node
          - name: Installing Babel
            run: npm install --save-dev @babel/core @babel/cli @babel/preset-env
          - name: Running build using preset.
            run: ./node_modules/.bin/babel ./src --out-dir ./dist
