name: Create xValidate for older browsers...
on:
    push:
        branches:
            - actions
    pull_request:
        branches:
            - actions

jobs:
    build:
        name: Creating Babel build...
        runs-on: ubuntu-latest
        steps:
          - name: Downloading current version of Node.js...
            run: sudo apt-get install -y nodejs
          - name: Installing Babel and getting config...
            run: ls && npm install
            working-directory: src
          - name: Get Babel config and run build
            run: npm run build
            working-directory: src
          - name: Saving build output to dist folder...
            uses: actions/upload-artifact@v1
            with:
                name: dist
                path: dist
